version: '3.8'

services:
  app:
    container_name: my_app_container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_TMDB_API_KEY=${NEXT_PUBLIC_TMDB_API_KEY}
        - RESEND_API_KEY=${RESEND_API_KEY}
    ports:
      - "3001:3000"
    # Commented out volumes to prevent overwriting built files
    # volumes:
    #   - .:/app
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      # Utilizza solo la chiave privata per sicurezza
      - TMDB_API_KEY=${TMDB_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
    restart: unless-stopped 