[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./app ./components ./lib"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_PUBLIC_TMDB_API_KEY = "c1fccb37538d185ce09b51ea97fe1da3"
  TMDB_API_KEY = "c1fccb37538d185ce09b51ea97fe1da3"
  NEXT_PUBLIC_SITE_URL = "https://mastroianni.app"

[functions]
  node_bundler = "esbuild"
  included_files = [".next/server/**/*", ".next/standalone/**/*"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Impostazioni per il deployment incrementale
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.images]
  compress = false

# Configurazione per immagini remote da TMDB
[images]
  remote_images = ["^(?:http(?:s)?:\\/\\/image\\.tmdb\\.org(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"]

# Cache per file statici
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects per gestire immagini ottimizzate
[[redirects]]
  from = "/_next/image"
  to = "/.netlify/images"
  status = 200
  force = true
  [redirects.query]
    url = ":url"
    w = ":width"
    q = ":quality" 